INSERT INTO roles (name) VALUES ('ADMIN'), ('MEMBER');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (1, 'burdukowskystas@gmail.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Станислав', 'Олегович', 'Бурдуковский', '1995-04-02', 'MALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (2, 'member@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Member', null, 'User', '1995-04-02', 'FEMALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (3, 'hero@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Hero', null, 'User', '1995-04-02', 'UNKNOWN');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (4, 'john.doe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'John', null, 'Doe', '1995-04-02', 'MALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (5, 'john.roe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'John', null, 'Roe', '1995-04-02', 'MALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (6, 'richard.roe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Richard', null, 'Roe', '1995-04-02', 'MALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (7, 'jane.doe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Jane', null, 'Doe', '1995-04-02', 'FEMALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (8, 'jane.roe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Jane', null, 'Roe', '1995-04-02', 'FEMALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (9, 'baby.doe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Baby', null, 'Doe', '1995-04-02', 'FEMALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (10, 'janie.doe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Janie', null, 'Doe', '1995-04-02', 'FEMALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (11, 'johnny.doe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Johnny', null, 'Doe', '1995-04-02', 'MALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (12, 'richard.doe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Richard', null, 'Doe', '1995-04-02', 'MALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (13, 'baby.roe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Baby', null, 'Roe', '1995-04-02', 'FEMALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (14, 'janie.roe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Janie', null, 'Roe', '1995-04-02', 'FEMALE');
INSERT INTO users (id, email, password, first_name, middle_name, last_name, date_birth, gender) VALUES (15, 'johnny.roe@example.com', '$2a$10$tYp8Q3ujZXSpM.d6xy6jaueLy/XSFVLaj6ms16xU2wnQ24UfT1dBe', 'Johnny', null, 'Roe', '1995-04-02', 'MALE');
INSERT INTO users_roles (user_id, role_name) VALUES (1, 'ADMIN'), (2, 'MEMBER'), (3, 'ADMIN'), (3, 'MEMBER');
INSERT INTO companies (id, name, description, owner_id) VALUES (1, 'Станислав Company', 'Test Desc', 1);
INSERT INTO companies (id, name, description, owner_id) VALUES (2, 'Jane Company', 'Test Desc', 2);
INSERT INTO categories (id, name, description) VALUES (1, 'Парикмахерские услуги', 'Парикмахерские услуги');
INSERT INTO categories (id, name, description) VALUES (2, 'Педикюр', 'Педикюр');
INSERT INTO services (id, name, description, category_id) VALUES (1, 'Био-выпрямление волос', 'Био-выпрямление волос', 1);
INSERT INTO services (id, name, description, category_id) VALUES (2, 'Био-завивка волос', 'Био-завивка волос', 1);
INSERT INTO services (id, name, description, category_id) VALUES (3, 'Аппаратный педикюр', 'Аппаратный педикюр', 2);
INSERT INTO services (id, name, description, category_id) VALUES (4, 'Гелиевый педикюр', 'Гелиевый педикюр', 2);